"""
Daily email digest.
Sends a summary of newly confirmed deals to the research team.
"""

import logging
from datetime import datetime, timezone
from typing import Optional

from config import get_config

logger = logging.getLogger(__name__)
config = get_config()


def send_daily_digest(conn):
    """Send daily digest of unalerted confirmed deals."""
    if not config.sendgrid_api_key or not config.alert_to_emails:
        logger.info("SendGrid not configured — skipping digest")
        return

    deals = _fetch_unalerted_deals(conn)
    if not deals:
        logger.info("No new confirmed deals to alert on")
        return

    html = _build_html(deals)
    subject = f"Nursing Home Acquisition Alert — {len(deals)} new deal(s) confirmed [{datetime.now().strftime('%b %d, %Y')}]"

    _send_email(subject, html)
    _mark_alerted(deals, conn)
    logger.info(f"Digest sent: {len(deals)} deals to {len(config.alert_to_emails)} recipients")


def _fetch_unalerted_deals(conn) -> list[dict]:
    with conn.cursor() as cur:
        cur.execute("""
            SELECT
                d.id, d.acquiring_entity, d.seller_entity, d.operator_names,
                d.facility_names, d.states, d.facility_count, d.deal_value_m,
                d.acquisition_date, d.confidence, d.stage,
                a.url AS article_url, a.title AS article_title,
                s.name AS source_name
            FROM deals d
            JOIN articles a ON a.id = d.article_id
            LEFT JOIN sources s ON s.id = a.source_id
            WHERE d.stage = 'confirmed'
              AND d.id NOT IN (
                  SELECT deal_id FROM alert_log WHERE alert_type = 'digest'
              )
            ORDER BY d.updated_at DESC
            LIMIT 50
        """)
        cols = [desc[0] for desc in cur.description]
        return [dict(zip(cols, row)) for row in cur.fetchall()]


def _build_html(deals: list[dict]) -> str:
    rows = ""
    for d in deals:
        states = ", ".join(d.get("states") or []) or "—"
        value = f"${d['deal_value_m']}M" if d.get("deal_value_m") else "—"
        facilities = d.get("facility_count") or "—"
        acquirer = d.get("acquiring_entity") or "Undisclosed"
        seller = d.get("seller_entity") or "—"
        date = str(d.get("acquisition_date") or "—")
        confidence_badge = {
            "high": "#EAF3DE", "partial": "#FAEEDA", "low": "#FCEBEB"
        }.get(d.get("confidence") or "low", "#F1EFE8")

        rows += f"""
        <tr>
          <td style="padding:12px;border-bottom:1px solid #eee">
            <strong>{acquirer}</strong><br>
            <span style="color:#666;font-size:12px">from {seller}</span>
          </td>
          <td style="padding:12px;border-bottom:1px solid #eee">{states}</td>
          <td style="padding:12px;border-bottom:1px solid #eee">{facilities}</td>
          <td style="padding:12px;border-bottom:1px solid #eee">{value}</td>
          <td style="padding:12px;border-bottom:1px solid #eee">{date}</td>
          <td style="padding:12px;border-bottom:1px solid #eee">
            <span style="background:{confidence_badge};padding:2px 8px;border-radius:4px;font-size:12px">
              {d.get('confidence') or 'low'}
            </span>
          </td>
          <td style="padding:12px;border-bottom:1px solid #eee">
            <a href="{d.get('article_url','')}">source</a>
          </td>
        </tr>"""

    return f"""
    <html><body style="font-family:sans-serif;max-width:900px;margin:0 auto;padding:20px">
      <h2 style="color:#1a1a1a">Nursing Home Acquisition Alert</h2>
      <p style="color:#666">{len(deals)} newly confirmed deal(s) as of {datetime.now().strftime('%B %d, %Y')}</p>
      <table style="width:100%;border-collapse:collapse;font-size:14px">
        <thead>
          <tr style="background:#f5f5f5">
            <th style="padding:10px;text-align:left">Acquirer / Seller</th>
            <th style="padding:10px;text-align:left">States</th>
            <th style="padding:10px;text-align:left">Facilities</th>
            <th style="padding:10px;text-align:left">Value</th>
            <th style="padding:10px;text-align:left">Date</th>
            <th style="padding:10px;text-align:left">Confidence</th>
            <th style="padding:10px;text-align:left">Source</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="color:#999;font-size:12px;margin-top:20px">
        This digest is auto-generated by the Nursing Home Acquisition Alert System.
      </p>
    </body></html>"""


def _send_email(subject: str, html: str):
    from sendgrid import SendGridAPIClient
    from sendgrid.helpers.mail import Mail, To

    message = Mail(
        from_email=config.alert_from_email,
        subject=subject,
        html_content=html,
    )
    message.to = [To(email) for email in config.alert_to_emails]

    sg = SendGridAPIClient(config.sendgrid_api_key)
    response = sg.send(message)
    logger.info(f"SendGrid response: {response.status_code}")


def _mark_alerted(deals: list[dict], conn):
    with conn.cursor() as cur:
        for deal in deals:
            cur.execute(
                "INSERT INTO alert_log (deal_id, alert_type) VALUES (%s, 'digest')",
                (deal["id"],)
            )
